# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
GET {{host}}/ping
Accept: application/json

###
GET {{host}}/api/tasks
Accept: application/json

###

GET {{host}}/api/tasks/done
Accept: application/json

###
GET {{host}}/api/tasks/search?q=micronaut
Accept: application/json

###
GET {{host}}/api/tasks/search?q=aws
Accept: application/json

###

POST {{host}}/api/tasks
Content-Type: application/json

{
    "summary" : "learn Micronaut",
    "description": "Micronaut works great with AWS Lambda and GraalVM"
}

###

GET {{host}}/api/tasks/1
Accept: application/json

###

PUT {{host}}/api/tasks/9/done
Content-Type: application/json

###

PUT {{host}}/api/tasks/7
Content-Type: application/json

{
    "summary" : "learn Spring",
    "description": "Spring works great with AWS Lambda and GraalVM",
    "done": false
}

###

PUT {{host}}/api/tasks/1
Content-Type: application/json

{
  "summary" : "learn Micronaut",
  "description": "Micronaut works great with AWS Lambda and GraalVM",
  "done": false
}

###
DELETE {{host}}/api/tasks/1

###
