micronaut:
  application:
    name: geecon-lambda-function

jackson:
  bean-introspection-module: true

datasources:
  default:
    url: jdbc:postgresql://localhost:34321/tasks
    driverClassName: org.postgresql.Driver
    username: postgres
    password: micronaut
    schema-generate: CREATE
    dialect: POSTGRES